---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: [--config=.github/linters/.flake8]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    # https://github.com/pre-commit/mirrors-mypy/issues/5
    hooks:
      - id: mypy
        name: mypy daily_checks
        files: ^daily_checks
      - id: mypy
        name: mypy setup
        files: ^setup
      - id: mypy
        name: mypy tasks
        files: ^tasks
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: [--rcfile=.github/linters/.python-lint]
